### ISSUE TITLE
Adapt Che-Code to the latest VS Code upstream changes

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21984]
### Is your task related to a problem? Please describe
There're [changes in VS Code upstream](https://github.com/microsoft/vscode/pull/172754) that conflicts with Che-Code build:

```
#13 358.3 [12:56:12] Error: /checode-compilation/src/vs/workbench/contrib/remote/browser/che/remote.ts(114,35): Property 'show' does not exist on type 'IDialogService'.
#13 358.3 [12:56:12] Error: /checode-compilation/src/vs/workbench/contrib/remote/browser/che/remote.ts(164,33): Property 'show' does not exist on type 'IDialogService'.
```

For more details, see the output of [the auto-rebase job](https://github.com/che-incubator/che-code/actions/runs/4078359010/jobs/7028473498).

### Describe the solution you'd like

Adaptat Che-Code to the upstream changes.
https://github.com/che-incubator/che-code#fixing-the-rebase-insiders-workflow

**Comment by azatsarynnyy** [comment]
@RomanNikitenko the upstream changes conflict with the changes from https://github.com/che-incubator/che-code/pull/163.
It requires just a minor refactoring. Could you take a look? To unblock the auto-rebase workflow.
