### ISSUE TITLE
[Typescript] `npm run tsc` command fails with `Cannot find name 'yamlSchema'` error

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse/che#21240]
### Describe the bug

`npm run tsc` command fails with `Cannot find name 'yamlSchema'` error after changes from https://github.com/eclipse/che/pull/21179 PR.

### Che version

7.44@latest

### Runtime

OpenShift

### Screenshots

![Selection_069](https://user-images.githubusercontent.com/7760565/157424603-9df5130d-883e-4a3a-ab12-c524bee83eb1.png)

### Installation method

chectl/next

### Environment

Linux
